# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='city',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='country',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='county',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='county',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcounties',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='subcounties',
            name='parent',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='county',
        ),
        migrations.DeleteModel(
            name='subcounties',
        ),
    ]
