# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20191127_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounties',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='subcounties',
            name='parent',
        ),
        migrations.DeleteModel(
            name='subcounties',
        ),
    ]
